"""Creación inicial

Revision ID: 6596dd294848
Revises: 9ec5e1738027
Create Date: 2025-11-20 00:34:26.224546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6596dd294848'
down_revision = '9ec5e1738027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datos_nuevos', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_column('datos_nuevos')

    # ### end Alembic commands ###
