"""empty message

Revision ID: 754a25cfbad3
Revises: 
Create Date: 2025-11-19 20:55:43.949668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754a25cfbad3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for SQLite ### 
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('alumno_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('aprobador_id', sa.Integer(), nullable=True))

        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

        # Foreign keys con nombres
        batch_op.create_foreign_key(
            'fk_solicitud_alumno',
            'alumno',
            ['alumno_id'],
            ['id']
        )

        batch_op.create_foreign_key(
            'fk_solicitud_aprobador',
            'usuario',
            ['aprobador_id'],
            ['id']
        )

        batch_op.drop_column('datos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - fixed ### 
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datos', sa.TEXT(), nullable=True))

        batch_op.drop_constraint('fk_solicitud_aprobador', type_='foreignkey')
        batch_op.drop_constraint('fk_solicitud_alumno', type_='foreignkey')

        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)

        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

        batch_op.drop_column('aprobador_id')
        batch_op.drop_column('alumno_id')
        batch_op.drop_column('motivo')

    # ### end Alembic commands ###
