"""empty message

Revision ID: 9ec5e1738027
Revises: 754a25cfbad3
Create Date: 2025-11-19 22:55:03.056623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec5e1738027'
down_revision = '754a25cfbad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(), nullable=True))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('creado_en')

    # ### end Alembic commands ###
